/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package motorph;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


public class EmployeeDirectoryPanel extends javax.swing.JPanel {
    public static void main(String[] args) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            JFrame frame = new JFrame("Employee Directory");
            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setSize(600, 500);
            frame.setLocationRelativeTo(null); // center on screen
            frame.add(new EmployeeDirectoryPanel()); // your JPanel
            frame.setVisible(true);
        });
    }

    private EmployeeModelFromFile employeeModel;
    
    public EmployeeDirectoryPanel(){
        initComponents();
        loadEmployeeDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableEmployee = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        tableEmployee.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tableEmployee.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadEmployeeDataToTable(){
        employeeModel = new EmployeeModelFromFile();
        Employee[] employees = employeeModel.getEmployeeModelList();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        for (Employee emp : employees){
            String empNo = emp.getEmpNo();
            String fullName = emp.getLastName() + "," + emp.getFirstName();
            String birthday = emp.getBirthday();
            
            model.addRow(new Object[]{empNo, fullName, birthday});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane tableEmployee;
    // End of variables declaration//GEN-END:variables
}
